@host = http://127.0.0.1:5000

### GET products
GET {{host}}/api/products

### Add product A
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "Produkt A",
  "price": 19.99
}

### Add product B
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "Produkt B",
  "price": 5.50
}

### Add to cart
POST {{host}}/api/cart/add
Content-Type: application/json

{
  "product_id": 1,
  "qty": 2
}

### GET cart
GET {{host}}/api/cart

### Checkout
POST {{host}}/api/checkout

### GET orders
GET {{host}}/api/orders
